### PR TITLE
Add continuous-integration

### PR DESCRIPTION
**Pull request by jrappen**
* [x] add continuous-integration
* [x] add `.gitattributes` to reduce pkg size shipped to users

### CODE REVIEW

**Comment by jrappen** [comment]
⚠️ This requires activating GitHub actions for this repo.

**Comment by braver** [comment]
Wow, thanks! I've always wanted to set this up. Let me check the status of GitHub actions here.

**Comment by braver** [comment]
I think this should "just work" ™️ as soon as we pull this PR. I'll just try and see..

**Comment by braver** [comment]
Well, it doesn't work at all. Actions are enabled for the repo. I'm totally in the dark about why it doesn't see the new workflow file and refuses to do anything.

**Comment by jrappen** [comment]
maybe because this is a fork?

**Comment by braver** [comment]
It does run now apparently. I forgot it would only run when you touch a file in the `paths`

**Comment by jrappen** [comment]
Yeah.

---

Here's the workflow badge, in case you want it:

```markdown
![CI](https://github.com/braver/SublimeSass/workflows/CI/badge.svg)
```

I didn't add it with this PR.

**Pull request merged**
